### ISSUE TITLE
Docker seem dead

### ISSUE THREAD

**Issue by billouetaudrey** [Helias/EPUB-to-PDF#5]
Hi, can you check it please : 

`Traceback (most recent call last):
  File "/epub_to_pdf/main.py", line 2, in <module>
    from telegram.ext import (
ImportError: cannot import name 'Filters' from 'telegram.ext' (/usr/local/lib/python3.10/dist-packages/telegram/ext/__init__.py)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
X connection to :1 broken (explicit kill or server shutdown).
Ignoring window icon: Size 65538 exceeds maximum xcb request length 0.
Ignoring window icon: Size 65538 exceeds maximum xcb request length 0.
The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 2 (No such file or directory) on X server ":1"
      after 346 requests (346 known processed) with 0 events remaining.`

**Comment by Helias** [comment]
`ImportError: cannot import name 'Filters' from 'telegram.ext'`
This seems more an issue about the python-telegram-bot library, we should put a fixed version in the Docker file in the step `pip3 install python-telegram-bot` compatible with that, or we could replace `Filters` with `filters`

**Comment by Helias** [comment]
hope I fixed it, check it now with the latest version

**Comment by billouetaudrey** [comment]
No fixed :'(

`[custom-init] No custom files found, skipping...
[ls.io-init] done.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.1.0 - built May 27 2023 18:53:23
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

Obt-Message: Xinerama extension is not present on the server
Traceback (most recent call last):
  File "/epub_to_pdf/main.py", line 75, in <module>
    main()
  File "/epub_to_pdf/main.py", line 62, in main
    updater = Updater(TOKEN, use_context=True)
TypeError: Updater.__init__() got an unexpected keyword argument 'use_context'
X connection to :1 broken (explicit kill or server shutdown).
`

**Comment by Helias** [comment]
should work now
